export class Test {
    id: number
    code?: number
    name?: string
    cptCode?: number
    preferredRequirement?: string
    alternateRequirement?: string
    minimumVolume?: string
    transportTemp?: string
    tat?: string
    methodology?: string
    daysPerformed?: string
    specialInstructions?: string
    comments?: string
    testIncluded?: string
    performingLab?: string
    clinicalSignificance?: string
}

export const Tests: Test[] = [
    {
        id: 0,
        code: 293,
        name: 'Opiates',
        cptCode: 80101,
        preferredRequirement: 'Random Urine',
        alternateRequirement: undefined,
        minimumVolume: '10mL (7mL)',
        transportTemp: 'R = 7 days',
        tat: undefined,
        methodology: 'Lateral Flow Chromatographic Immunoassay',
        daysPerformed: 'Mon-Fri',
        specialInstructions: 'Submit urine in a sterile container',
        comments: undefined,
        testIncluded: undefined,
        performingLab: undefined,
        clinicalSignificance: undefined
    },
    {
        id: 1,
        code: 999,
        name: 'Alochol',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
    },
    {
        id: 2,
        code: 999,
        name: 'Benzodiazepine',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
        
    },
    {
        id: 3,
        code: 999,
        name: 'Cannabinoids (THC)',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
        
    },
    {
        id: 4,
        code: 999,
        name: 'Estradiol',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
        
    },
    {
        id: 5,
        code: 999,
        name: 'Folate (Folic Acid)',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
        
    },
    {
        id: 6,
        code: 999,
        name: 'Glucose (Fasting)',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
        
    },
    {
        id: 7,
        code: 999,
        name: 'Hemoglobin',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
        
    },
    {
        id: 8,
        code: 999,
        name: 'Iron',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
        
    },
    {
        id: 9,
        code: 999,
        name: 'Magnesium',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
        
    },
    {
        id: 10,
        code: 999,
        name: 'Mono Screen',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
        
    },
    {
        id: 11,
        code: 999,
        name: 'Phosphorus',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
        
    },
    {
        id: 12,
        code: 999,
        name: '<testName>',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
        
    },
    {
        id: 13,
        code: 999,
        name: '<testName>',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
        
    },
    {
        id: 14,
        code: 999,
        name: '<testName>',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
        
    },
    {
        id: 15,
        code: 999,
        name: '<testName>',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
        
    },
    {
        id: 16,
        code: 999,
        name: '<testName>',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
        
    },
    {
        id: 17,
        code: 999,
        name: '<testName>',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
        
    },
    {
        id: 18,
        code: 999,
        name: '<testName>',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
        
    },
    {
        id: 19,
        code: 999,
        name: '<testName>',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
        
    },
    {
        id: 20,
        code: 999,
        name: '<testName>',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
        
    },
    {
        id: 21,
        code: 999,
        name: '<testName>',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
        
    },
    {
        id: 22,
        code: 999,
        name: '<testName>',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
        
    },
    {
        id: 23,
        code: 999,
        name: '<testName>',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
        
    },
    {
        id: 24,
        code: 999,
        name: '<testName>',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
        
    },
    {
        id: 25,
        code: 999,
        name: '<testName>',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
        
    },
    {
        id: 26,
        code: 999,
        name: '<testName>',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
        
    },
    {
        id: 27,
        code: 999,
        name: '<testName>',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
        
    },
    {
        id: 28,
        code: 999,
        name: '<testName>',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
        
    },
    {
        id: 29,
        code: 999,
        name: '<testName>',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
        
    },
    {
        id: 30,
        code: 999,
        name: '<testName>',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
        
    },
    {
        id: 31,
        code: 999,
        name: '<testName>',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
        
    },
    {
        id: 32,
        code: 999,
        name: '<testName>',
        cptCode: 99999,
        preferredRequirement: '<preferredRequirement>',
        alternateRequirement: '<alternateRequirement>',
        minimumVolume: '<minimumVolume>',
        transportTemp: '<transportTemp>',
        tat: '<tat>',
        methodology: '<methodology>',
        daysPerformed: '<daysPerformed>',
        specialInstructions: '<specialInstructions>',
        comments: '<comment>',
        testIncluded: '<testIncluded>',
        performingLab: '<performingLab>',
        clinicalSignificance: '<clinicalSignificance>'
        
    }
];